# Конфигурация для Render
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: ai-telegram-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "8275482287:AAEO9YvDNd8Tc94UAthO7w8193ABog-Dc40"
      - key: GEMINI_API_KEY
        value: "AQ.Ab8RN6J_BZkjjI8W5-e6BUFgvV46rngEryETviVGTrSoJIAiIw"
      - key: API_ID
        value: "32146160"
      - key: API_HASH
        value: "ae96a4fa8b6c045b6c79c4f5b15ceb34"
